fix(action): replace set-output with environment variable
WyriHaximus/github-action-next-semvers pull request #55
Opened 2022-12-14 03:08 UTC by dargmuesli

Resolves #53.

Please try it though / use it as a starting point for an improved implementation.

2022-12-14 07:38 UTC, WyriHaximus requested changes
Thanks for filing these changes. I've requested a few changes. As per your comment https://github.com/WyriHaximus/github-action-next-semvers/issues/53#issuecomment-1350309082 PHP isn't you language but that is fine I gladly guide you through it or take this as a base. There where also a few things off for the action files. 

You might know or not know this but the `>>` in shell takes the output (from STDOUT) and writes it to something on the filesystem. In this case it is the file defined in `$GITHUB_OUTPUT` so the way you are currently implementing this doesn't do that because it is part of the output.

2022-12-14 07:38 UTC, WyriHaximus commented on src/Next.php
> +        $output .= '"v_minor=v' . $version->incrementMinor() . '" >> $GITHUB_OUTPUT' . PHP_EOL;
Change all of them in this file to this format, and then in `next.php` in the root of this repository replace the `echo` with a file_put_contents as in: https://github.com/WyriHaximus/github-action-supported-php-versions/blob/940773a095e0d019bca8d75262755dcfbb3092f1/versions.php#L27

```suggestion
        $output .= '"v_minor=v' . $version->incrementMinor() . "\"\n";
```

2022-12-14 07:38 UTC, WyriHaximus commented on .github/workflows/ci.yml
> +            printf "ref=%s >> $GITHUB_OUTPUT" $ref
```suggestion
            printf "ref=%s" $ref >> $GITHUB_OUTPUT 
```

2022-12-14 07:38 UTC, WyriHaximus commented on .github/workflows/ci.yml
> +          echo "ref=${GITHUB_REF##*/} >> $GITHUB_OUTPUT"
```suggestion
          echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
```

2022-12-14 07:55 UTC, dargmuesli commented
Thank you for the quick feedback! I hope I understood your suggestions correctly? :)

2022-12-14 22:10 UTC, WyriHaximus requested changes

2022-12-14 22:10 UTC, WyriHaximus commented on src/Next.php
> +            $output .= '"v_patch=v' . $version->incrementPatch();
Needs to be on all of them, something else might write to it as well after this action and that will mess it potentially up.

2022-12-14 22:16 UTC, dargmuesli commented on src/Next.php
> +            $output .= '"v_patch=v' . $version->incrementPatch();
done

2022-12-14 22:42 UTC, WyriHaximus commented
> Thank you for the quick feedback! I hope I understood your suggestions correctly? :)

Yes, you did :D. It mostly looks good aside from that one comment and the change that needs to be made on this line: https://github.com/WyriHaximus/github-action-next-semvers/blob/master/next.php#L14

2022-12-14 22:46 UTC, dargmuesli commented
What else needs to be done there? :sweat_smile: I thought I did the change as intended :see_no_evil:

2022-12-14 22:55 UTC, WyriHaximus commented
> What else needs to be done there? 😅 I thought I did the change as intended 🙈

Well you did, except that you still need to change https://github.com/WyriHaximus/github-action-next-semvers/blob/master/next.php#L14 to 
```php
file_put_contents(getenv('GITHUB_OUTPUT'), Next::run($versionString, \getenv('INPUT_STRICT') === 'false' ? false : true), FILE_APPEND);
```

2022-12-14 23:52 UTC, dargmuesli commented
I think we have a misunderstanding. That line is already be changed as far as I get.

2022-12-14 23:52 UTC, dargmuesli commented on next.php
> +    file_put_contents(getenv('GITHUB_OUTPUT'), Next::run($versionString, \getenv('INPUT_STRICT') === 'false' ? false : true), FILE_APPEND);
Are we talking about this change?

2022-12-16 10:48 UTC, WyriHaximus commented on next.php
> +    file_put_contents(getenv('GITHUB_OUTPUT'), Next::run($versionString, \getenv('INPUT_STRICT') === 'false' ? false : true), FILE_APPEND);
Yes, wait did I completely miss that? I'm so sorry, I had a rough couple of weeks and I was expecting the file under the directories in the tree on the left :facepalm:

2022-12-16 10:49 UTC, WyriHaximus approved these changes
Yeah completely missed that, I'll merge and get this released later today. Thank you for all the work on it :+1: .

2022-12-16 10:53 UTC, merged